language: python
dist: xenial
python: 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install -r requirements-dev.txt
  - pip install pipenv
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=licitagiassi

after_success:
  - pipenv run codecov


